name: Ephemeral PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    # Required to request the OIDC token from GitHub
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::044889053561:role/Ephemeral-Github-Project-Role
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Terraform Init
        run: terraform init -backend-config="key=pr-${{ github.event.pull_request.number }}/terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -var="pr_number=${{ github.event.pull_request.number }}" -auto-approve

      - name: Get EC2 IP Address
        run: |
          EC2_IP=$(terraform output -raw public_ip)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EPHEMERAL_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
        ANSIBLE_HOST_KEY_CHECKING: "false" # Bypasses the strict host key prompt for dynamic IPs
        run: ansible-playbook -i "${{ env.EC2_IP }}," -u ec2-user --private-key ~/.ssh/id_rsa playbook.yml
